name: HDX/CKAN types checker

on:
  push:
    branches: [ '**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.10'

permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Upgrade SetupTools
        run: pip install --upgrade setuptools

      - name: Install Python deps
        run: pip install -r requirements.txt -r dev-requirements.txt -e.

      - name: Install node deps
        run: npm ci

      - name: Check types
        run: npx pyright
