name: HDX/CKAN linter

on:
  push:
    branches: [ '**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]

jobs:
  linter:
    runs-on: ubuntu-latest

    env:
      CONFIG_FILE: pyproject.toml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ruff linter
        run: pip install ruff

      - name: Run ruff linter for ckanext-hdx_dataviz
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_dataviz
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_hxl_preview
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_hxl_preview
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_office_preview
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_office_preview
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_org_group
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_org_group
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_package
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_package
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_pages
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_pages
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_search
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_search
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_service_checker
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_service_checker
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_theme
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_theme
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_user_extra
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_user_extra
        continue-on-error: true

      - name: Run ruff linter for ckanext-hdx_users
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-hdx_users
        continue-on-error: true

      - name: Run ruff linter for ckanext-sitemap
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-sitemap
        continue-on-error: true

      - name: Run ruff linter for ckanext-ytp-request
        run: ruff check --config ${{ env.CONFIG_FILE }} ckanext-ytp-request
        continue-on-error: true
