name: HDX/CKAN types checker

on:
  push:
    branches: [ '**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    env:
      CONFIG_FILE: /srv/ckan/pyproject.toml

    strategy:
      matrix:
        directories:
          - /srv/ckan/ckan
          - /srv/ckan/ckanext-abc_dataviz
          - /srv/ckan/ckanext-abc_hxl_preview
          - /srv/ckan/ckanext-abc_office_preview
          - /srv/ckan/ckanext-abc_org_group
          - /srv/ckan/ckanext-abc_package
          - /srv/ckan/ckanext-abc_pages
          - /srv/ckan/ckanext-abc_search
          - /srv/ckan/ckanext-abc_service_checker
          - /srv/ckan/ckanext-abc_theme
          - /srv/ckan/ckanext-abc_user_extra
          - /srv/ckan/ckanext-abc_users
          - /srv/ckan/ckanext-sitemap
          - /srv/ckan/ckanext-ytp-request

    steps:
      - uses: actions/checkout@v3
      - name: Building CKAN docker image
        run: docker-compose build ckan

      - name: Spinning up docker-compose stack
        run: |
          docker-compose up -d
          sleep 10

      - name: Installing HDX/CKAN PY3 dev-requirements
        run: docker-compose exec -T ckan pip install -r /srv/ckan/dev-requirements.txt

      - name: Install Node.js and npm
        run: |
          docker-compose exec -T ckan bash -c "
          curl -sL https://deb.nodesource.com/setup_22.x | bash -
          apt-get install -y nodejs
          npm install -g npm
          npm install -g pyright
          "

      - name: Check types for ${{ matrix.directories }}
        run: docker-compose exec -T ckan pyright -p ${{ env.CONFIG_FILE }} ${{ matrix.directories }}
        continue-on-error: true
