name: HDX/CKAN linter

on:
  push:
    branches: [ '**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]

jobs:
  linter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directories:
          - ckanext-abc_dataviz
          - ckanext-abc_hxl_preview
          - ckanext-abc_office_preview
          - ckanext-abc_org_group
          - ckanext-abc_package
          - ckanext-abc_pages
          - ckanext-abc_search
          - ckanext-abc_service_checker
          - ckanext-abc_theme
          - ckanext-abc_user_extra
          - ckanext-abc_users
          - ckanext-sitemap
          - ckanext-ytp-request

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ruff linter
        run: |
          pip install ruff

      - name: Run ruff linter for ${{ matrix.directories }}
        run: |
          ruff check ${{ matrix.directories }}
        continue-on-error: true
