name: HDX/CKAN types checker

on:
  push:
    branches: [ '**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building CKAN docker image
        run: docker-compose build ckan
      - name: Spinning up docker-compose stack
        run: |
          docker-compose up -d
          sleep 10
      - name: Installing HDX/CKAN PY3 dev-requirements
        run: docker-compose exec -T ckan pip install -r /srv/ckan/dev-requirements.txt
      - name: Install node deps
        run: docker-compose exec -T npm ci
      - name: Check types
        run: docker-compose exec -T npx pyright
